model:
  arch: cheetah_llama2
  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "bf16"
  freeze_vit: True
  freeze_qformer: True
  freeze_llama_proj: True

  # Q-Former
  num_query_token: 32

  # llama2
  llama_model: "path_to_Llama-2-7b-chat-hf"

  # generation configs
  prompt: ""

preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip2_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
