CONTROLLER_HEART_BEAT_EXPIRATION = 90
WORKER_HEART_BEAT_INTERVAL = 30
WORKER_API_TIMEOUT = 20

LOGDIR = "/home/xupeng/VLP_web/server_utils/runtime_log"
CONVERSATION_SAVE_DIR = '/nvme/data1/VLP_web_data/conversation_data'


rules_markdown = """ ### Rules
- Vote for large multi-modality models on visual question answering.
- Load an image and ask a question. Only one question is supported per round.
- Two models are anonymous before your vote.
- Click “Clear history” to start a new round.
- [[GitHub]](https://github.com/OpenGVLab/Multi-modality-Arena)
"""


notice_markdown = """ ### Terms of use
By using this service, users are required to agree to the following terms: The service is a research preview intended for non-commercial use only. It only provides limited safety measures and may generate offensive content. It must not be used for any illegal, harmful, violent, racist, or sexual purposes. **The service collects user dialogue data and reserves the right to distribute it under a Creative Commons Attribution (CC-BY) license.** The demo works better on desktop devices with a wide screen.
"""


license_markdown = """ ### License
The service is a research preview intended for non-commercial use only, subject to the model [License](https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md) of LLaMA, [Terms of Use](https://openai.com/policies/terms-of-use) of the data generated by OpenAI, and [Privacy Practices](https://chrome.google.com/webstore/detail/sharegpt-share-your-chatg/daiacboceoaocpibfodeljbdfacokfjb) of ShareGPT. Please contact us if you find any potential violation.
"""